stages:
  - deploy

# Настройки деплоя для основного домена (ветка main)
deploy_production:
  stage: deploy
  tags:
    - deploy
  script:
    - cd /var/www/davidgelmut.ru
    - git fetch origin
    - git reset --hard origin/main
    - docker compose down
    - docker compose up -d --build
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

# Настройки деплоя для поддомена dev (ветка dev)
deploy_development:
  stage: deploy
  tags:
    - deploy
  script:
    - cd /var/www/dev.davidgelmut.ru
    - git fetch origin
    - git reset --hard origin/dev
    - docker compose down
    - docker compose up -d --build
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"
